### ISSUE TITLE
Stopped working in Chrome

### ISSUE THREAD

**Issue by Maryassad** [sylouuu/chrome-tab-modifier#66] opened 2017-03-10 11:22 UTC
I love TabModifier, using it for a few weeks but suddenly today it's stopped working!

I had all the icons set up - but have just reset. 

I've tried creating new rules, to no avail. I've even removed the extension, re-installed it, created different rules with other images but still no luck?

Any issues?

Thanks

**Comment by Maryassad** [comment] 2017-03-10 12:02
Ok I've found a weird workaround, for some pages you have to grab the loading page so that instead of the ending of the link being:
- &path=/calendar

It will be:
- #path=%2fcalendar

**Comment by sylouuu** [comment] 2017-03-10 14:47
Hello @Maryassad,

Glad it's OK. So was it a problem about your URL fragment? You can close the issue when its solved.

Best

**Comment by Maryassad** [comment] 2017-03-10 15:19
Hi there,

I don't think the URL was the issue - as it was working for weeks, then
just stopped working today.

I only discovered a the work around by 'grabbing' the URL before it loaded
(with the % instead of the /) which seemed to do the trick.

So rather than a fix, I thought that information might help you find the
issue?

So for example if others tried the app with any MS365 web links (mail,
calendar etc) they will have the same experience as me, but won't realise
the workaround - therefore will just believe the app does not work.

Hope that helps clarify?
Mary


All the best

Mary

Mary Assad | 07956419306
assadmary@gmail.com
Linkedin: Mary Assad
<https://www.linkedin.com/wvmx/profile/rankings?trk=wvmx-profile>

**Comment by sylouuu** [comment] 2017-03-10 16:05
No new version has been recently released.

I don't know what I can do here, first time someone is reporting somethink like that.

**Comment by bottomlineusa** [comment] 2017-03-10 16:14
That is not correct.  I reported the same issue.  I thought it was resolved.  It is not.
 
Victoria

**Comment by sylouuu** [comment] 2017-03-10 16:29
I need a real website, with a rule to test for analysing purpose, can't do anything just by talking. :)

I have to reproduce the behavior you describe.

**Comment by bottomlineusa** [comment] 2017-03-10 16:37
Unfortunately, tab modifier does not work with websites that require a sign in and that is where most of tab modifier is useful to me.
 
Victoria

**Comment by Maryassad** [comment] 2017-03-10 16:52
Hi Sylouu

If you test this issue with any MS365 / outlook account you will be able to replicate the issue - as Victoria says, it looks like they are sites that require a sign-in. 

For the last few weeks the usual link was working fine:
https://outlook.office.com/owa/?realm=(companynamehidden.com)&path=/calendar 

It stopped working yesterday -  and by fluke I realised it would only work if you quickly grab and copy and paste the 'LOADING' URL, not the 'SETTLED' URL which is then:
https://outlook.office.com/owa/?realm=(companynamehidden.com)#path=%2fcalendar

I've noticed differences between the links - is that the '&' is now a '#' and the '/' is now a '%2f'
(look at the link endings - original: &path=/calendar  - but now: #path=%2fcalendar)

This then fixes the favicon disappearing.

However users would not realise this rather bizarre workaround,  so hope that helps to fix this bug.

@Victoria hopefully this will be a temporary workaround for you too, it worked for me.

All the best

Mary

**Comment by sylouuu** [comment] 2017-03-10 17:20
Thanks @Maryassad.

I'm not sure if I can fix, as you said, it worked before.

What about changing your URL fragment with a less restrictive match? Or buy specifying a regular expression (advanced usage). You may try something to avoid to deal with "special characters".

**Comment by bottomlineusa** [comment] 2017-03-10 18:12
@ Mary, thank you,  It was a workaround that I had discovered and thought would work when I first experienced this issue.  But, the workaround does not usually work or stick if it does.  I contacted Syl about this a while ago and he gave the same reply then, that he could not fix this unless he could replicate it.  Of course, I cannot give him my login to test this.  
 
It’s a shame as this would be an awesome program and I would be happy to pay for it…if it worked as needed.
 
Victoria

**Comment by Maryassad** [comment] 2017-03-10 20:54
Hi Sylouu

Thanks for your suggestions, but I don't have a choice of the URL fragment, otherwise the page won't load. I also tried specifying a regular expression (advanced usage) but that doesn't work either. 

Basically we want the mail, calendar and other apps within outlook to have different favicons from eachother. If it is shortened etc it would not specify which link it was as each ends in 'calendar' etc. 

At least you now know what users are experiencing - which may happen to others when trying to use outlook / sign in pages, up to you / the team for a fix I guess!

@victoria - thanks, at least we tried, the workaround is working for now fingers crossed it stick / or will get fixed one day!


Mary

**Comment by bottomlineusa** [comment] 2017-03-10 21:12
@ Sylouuu ...I train others in setting up and using QBO (QuickBooks online).  There are **many** users of this program and if Tab-Modifier would work with QBO, it would be a big hit.  Not only would I promote it to QBO users, but I would include it in my training sessions.  

To get tab-modifier to work with QBO, you can sign up for a trial account (30 days) and test it.  That way you can fix the issue, and might even discover what needs to be done to make it work with other sign in websites.  [www.quickbooks.com/free-trial.](www.quickbooks.com/free-trial)  Try with the PLUS version.

As I mentioned before, I would be willing to pay for tab-modifier if it worked consistently with QBO, and I know others would too.  The time and frustration tab-modifier would save would make it worth it.

**Comment by sylouuu** [comment] 2017-03-10 21:25
I'll take a look on QBO, should I test something in particular? Can you give me a rule that doesn't work as expected? Do you have a step-by-step for me like: set up this rule, go to {url}...

@Maryassad I'm alone on this project, its a personal one and working on it in my spare time.

@bottomlineusa Tab Modifier will always be free ;)

**Comment by Maryassad** [comment] 2017-03-10 22:07
Thanks and good luck with your project

Mary

**Comment by bottomlineusa** [comment] 2017-03-10 22:24
Thank you Syl.  It is certainly at lot easier to promote the product if there is no charge.  Of course, I would encourage those who experience the value to donate for your time.  :-)   

What would make tab-modifier useful is to be able to open any form or report in QBO and drag that tab to the Bookmarks toolbar, and name with tab-modifier so all they have to do is open a new tab, click the bookmark and they will know what is on that tab.  When working in QBO, often different forms and reports need to be opened simultaneously.  For example, the write "Check" form, and the "Vendor" list. And the Profit and Loss and Balance Sheet.   Here is a screenshot of what I mean.
![qbo_bookmarks](https://cloud.githubusercontent.com/assets/25965015/23815438/1670747e-059d-11e7-8cef-984bf0ce514c.jpg)

The names on the bookmarks should show up on the tabs with the matching names so it is clear to see what is on open in each tab.  This will help tremendously when having multiple tabs open using QBO.

**Comment by bottomlineusa** [comment] 2017-03-10 22:36
I can give you more directions once you’ve created your test account and let me know specific questions you have.
 
Victoria

**Comment by sylouuu** [comment] 2017-03-11 10:41
I'm really confused.

@bottomlineusa What's wrong in your screenshot? Missing colored icons?

I just created an account, pages are well named by default, why do you need to rewrite?

I've added a rule on one page with a custom colored icon and it's OK.

Tab Modifier is not so smart, it compares strings and there is no bug with that as this is the Javascript API.

It's really hard for me to understand if you are experiencing a real Tab Modifier bug or if you are experiencing an edge-case and you expect something that is wrong.

@Maryassad As I said, it compares the current URL with your URL fragment, `path=/calendar` is not equal to `path=%2fcalendar` so it's an expected behavior to see your rule ignored. The website has to redirect you to the end URL and your rule will be triggered. For your curiosity it's caused by the website itself:

```php
echo http_build_query(['path' => '/calendar']); // path=%2Fcalendar
```


I do not know what else I can do. Sorry for my english.

Best

**Comment by sylouuu** [comment] 2017-03-11 11:03
@bottomlineusa Ok maybe I found something, tell me if I'm right. If you open a new tab and click on your bookmark, Tab Modifier must trigger the associated rule. But when you go to this page from the website (by clicking on a links from the left sidebar) the icon you have specified is the old one from the first page load? However the page title seems correct.

It happens because Quickbooks is a modern web-app and when you are browsing your private space, it changes the current **URL** and the title **dynamically**. Tab Modifier already supports websites with dynamic titles but not dynamic URLs.

That said, I don't think both of your "problems" are related. Is that more clear for you @Maryassad @bottomlineusa?

**Comment by bottomlineusa** [comment] 2017-03-11 15:41
Some of the tabs do have names by default.  However, If you run reports, you’ll see the reports show the company name in the tab, not the report name (such as Profit & Loss or Balance Sheet).  

Not sure why you assume there is something wrong with my screenshot.   I wasn’t using the colors and did not say there was a problem with colors.  I said the tab names don’t always work.   

I appreciate your looking at this.   Sorry you don’t understand what I am trying to describe.  

Good luck with your product.

**Comment by sylouuu** [comment] 2017-03-23 16:46
Hello @Maryassad,

I close this issue as I don't know what can I do for it.

Best

**Closed by sylouuu** 2017-03-23 16:46 UTC
Labels: type: question
